---
# Core configuration
# Core configuration. Not editable live. Require a restart of the server.
# Usually located at `/etc/snooze/server/core.yaml`

# Listening address (string)
# IPv4 address on which Snooze process is listening to
listen_addr: 0.0.0.0

# Port (integer)
# Port on which Snooze process is listening to
port: 5200

# Debug (boolean)
# Activate debug log output
debug: false

# Bootstrap database (boolean)
# Populate the database with an initial configuration
bootstrap_db: true

# Unix socket (string)
# Listen on this unix socket to issue root tokens
unix_socket: /var/run/snooze/server.socket

# No login (boolean)
# Disable Authentication (everyone has admin priviledges)
no_login: false

# Audit excluded paths (array[string])
# A list of HTTP paths excluded from audit logs. Any paththat starts with a path in this list will be excluded.
audit_excluded_paths:
- /api/patlite
- /metrics
- /web

# Process plugins (array[string])
# List of plugins that will be used for processing alerts. Order matters.
process_plugins:
- rule
- aggregaterule
- snooze
- notification

# Database (object)
# database: 

# Init sleep (integer)
# Time to sleep before retrying certain operations (bootstrap, clustering)
init_sleep: 5

# Create root user (boolean)
# Create a *root* user with a default password *root*
create_root_user: false

# SSL configuration
ssl:  # SslConfig
  # SSL configuration

  # Enabled (boolean)
  # Enabling TLS termination
  enabled: false

  # Certificate file (string)
  # Path to the x509 PEM style certificate to use for TLS termination
  # Example #0:
  # certfile: /etc/pki/tls/certs/snooze.crt
  # Example #1:
  # certfile: /etc/ssl/certs/snooze.crt

  # Key file (string)
  # Path to the private key to use for TLS termination
  # Example #0:
  # keyfile: /etc/pki/tls/private/snooze.key
  # Example #1:
  # keyfile: /etc/ssl/private/snooze.key

# Web server configuration
web:  # WebConfig
  # The subconfig for the web server (snooze-web)

  # Enabled (boolean)
  # Enable the web interface
  enabled: true

  # Path (string)
  # Path to the web interface dist files
  path: /opt/snooze/web

# Cluster configuration
cluster:  # ClusterConfig
  # Configuration for the cluster

  # Enabled (boolean)
  # Enable clustering. Required when running multiple backends
  enabled: true

  # Members (array)
  # List of snooze servers in the cluster. If the environment variable is provided, a special syntax is expected (`"<host>:<port>,<host>:<port>,..."`).
  # Example #0:
  # members:
  # - host: host01
  #   port: 5200
  # - host: host02
  #   port: 5200
  # - host: host03
  #   port: 5200
  # Example #1:
  members: snooze1:5200,snooze2:5200,snooze3:5200

# Backup configuration
backup:  # BackupConfig
  # Configuration for the backup job

  # Enabled (boolean)
  # Enable backups
  enabled: true

  # Path (string)
  # Path to store database backups
  path: /var/lib/snooze

  # Excludes (array[string])
  # Collections to exclude from backups
  excludes:
  - record
  - stats
  - comment
  - secrets

